spring:
  datasource:
    url: jdbc:mysql://database-1.cwjgguimby5v.ap-northeast-2.rds.amazonaws.com:3306/muvi?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: 12345678
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

server:
  port: 8080