spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

server:
  port: 8080